// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaVirtual.Api.Infrastructure.Persistence;

#nullable disable

namespace TiendaVirtual.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso total, incluidos usuarios y roles.",
                            IsSystem = true,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mantiene categorías y productos.",
                            IsSystem = false,
                            Name = "Catálogo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mantiene proveedores y sus costos; ve el catálogo.",
                            IsSystem = false,
                            Name = "Compras"
                        });
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Permission")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 2,
                            Permission = "categories.manage"
                        },
                        new
                        {
                            RoleId = 2,
                            Permission = "products.manage"
                        },
                        new
                        {
                            RoleId = 2,
                            Permission = "suppliers.view"
                        },
                        new
                        {
                            RoleId = 3,
                            Permission = "suppliers.manage"
                        },
                        new
                        {
                            RoleId = 3,
                            Permission = "products.view"
                        },
                        new
                        {
                            RoleId = 3,
                            Permission = "categories.view"
                        });
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Almacenamiento"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Memoria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Procesadores"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gráficas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Energía"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tarjetas madre"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accesorios"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Periféricos"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SSD NVMe",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "SSD SATA",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "RAM escritorio",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "RAM portátil",
                            ParentId = 2
                        });
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Kingston",
                            CategoryId = 9,
                            Description = "Unidad M.2 2280 PCIe 4.0, hasta 3500 MB/s de lectura. Ideal para revivir un equipo lento.",
                            IsActive = true,
                            Name = "SSD NVMe 1 TB Kingston NV2",
                            Price = 245000m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Crucial",
                            CategoryId = 10,
                            Description = "Disco de 2,5\" para portátiles y torres que no tienen ranura M.2.",
                            IsActive = true,
                            Name = "SSD SATA 480 GB Crucial BX500",
                            Price = 135000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Kingston",
                            CategoryId = 11,
                            Description = "Módulo DIMM para escritorio. Compatible con la mayoría de placas Intel y AMD recientes.",
                            IsActive = true,
                            Name = "Memoria RAM DDR4 16 GB 3200 MHz",
                            Price = 189000m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Crucial",
                            CategoryId = 12,
                            Description = "Módulo para portátil, 3200 MHz. La mejora más barata para un portátil que se queda corto.",
                            IsActive = true,
                            Name = "Memoria RAM SODIMM DDR4 8 GB",
                            Price = 99000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            Brand = "AMD",
                            CategoryId = 3,
                            Description = "6 núcleos y 12 hilos, socket AM4. Excelente relación precio/rendimiento para gaming y oficina.",
                            IsActive = true,
                            Name = "Procesador AMD Ryzen 5 5600",
                            Price = 520000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 6,
                            Brand = "MSI",
                            CategoryId = 4,
                            Description = "Juegos en 1080p con DLSS 3 y bajo consumo (115 W). Requiere fuente de 550 W.",
                            IsActive = true,
                            Name = "Tarjeta gráfica RTX 4060 8 GB",
                            Price = 1450000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Cooler Master",
                            CategoryId = 5,
                            Description = "Fuente ATX certificada, suficiente para equipos gamer de gama media.",
                            IsActive = true,
                            Name = "Fuente de poder 650 W 80+ Bronze",
                            Price = 275000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 8,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Description = "Micro-ATX con PCIe 4.0 y dos ranuras M.2. Pareja natural del Ryzen 5 5600.",
                            IsActive = true,
                            Name = "Board B550M AM4",
                            Price = 480000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Arctic",
                            CategoryId = 7,
                            Description = "Para mantenimiento de procesadores y tarjetas gráficas. Rinde varias aplicaciones.",
                            IsActive = true,
                            Name = "Pasta térmica Arctic MX-4 4 g",
                            Price = 32000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Redragon",
                            CategoryId = 8,
                            Description = "Formato TKL, switches rojos, retroiluminación. Resistente para uso diario.",
                            IsActive = true,
                            Name = "Teclado mecánico Redragon Kumara",
                            Price = 165000m,
                            Stock = 12
                        });
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Capacidad",
                            ProductId = 1,
                            Value = "1 TB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Interfaz",
                            ProductId = 1,
                            Value = "PCIe 4.0 NVMe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Formato",
                            ProductId = 1,
                            Value = "M.2 2280"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Capacidad",
                            ProductId = 2,
                            Value = "480 GB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interfaz",
                            ProductId = 2,
                            Value = "SATA III"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Formato",
                            ProductId = 2,
                            Value = "2,5\""
                        },
                        new
                        {
                            Id = 7,
                            Name = "Capacidad",
                            ProductId = 3,
                            Value = "16 GB"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tipo",
                            ProductId = 3,
                            Value = "DDR4"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Velocidad",
                            ProductId = 3,
                            Value = "3200 MHz"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Formato",
                            ProductId = 3,
                            Value = "DIMM"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Capacidad",
                            ProductId = 4,
                            Value = "8 GB"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tipo",
                            ProductId = 4,
                            Value = "DDR4"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Velocidad",
                            ProductId = 4,
                            Value = "3200 MHz"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Formato",
                            ProductId = 4,
                            Value = "SODIMM"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Socket",
                            ProductId = 5,
                            Value = "AM4"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Núcleos",
                            ProductId = 5,
                            Value = "6"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Memoria",
                            ProductId = 6,
                            Value = "8 GB"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Consumo",
                            ProductId = 6,
                            Value = "115 W"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Potencia",
                            ProductId = 7,
                            Value = "650 W"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Certificación",
                            ProductId = 7,
                            Value = "80+ Bronze"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Formato",
                            ProductId = 7,
                            Value = "ATX"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Socket",
                            ProductId = 8,
                            Value = "AM4"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Formato",
                            ProductId = 8,
                            Value = "Micro-ATX"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Peso",
                            ProductId = 9,
                            Value = "4 g"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Formato",
                            ProductId = 10,
                            Value = "TKL"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Color",
                            ProductId = 10,
                            Value = "Negro"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Conexión",
                            ProductId = 10,
                            Value = "USB"
                        });
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Suppliers.ProductSupplier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ProductId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductSuppliers");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.AdminUser", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Access.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.RolePermission", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Access.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Category", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Catalog.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Product", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.ProductAttribute", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Catalog.Product", null)
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Review", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Catalog.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Suppliers.ProductSupplier", b =>
                {
                    b.HasOne("TiendaVirtual.Api.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TiendaVirtual.Api.Domain.Suppliers.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Access.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TiendaVirtual.Api.Domain.Suppliers.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
